### ISSUE TITLE
original yaml broken for updates.

### ISSUE THREAD

**Issue by haldi4803** [smarthomeshop/ultimatesensor-mini#12]
Tried to update the Sensor.
Got an error about the 16mb

Original yaml
```
substitutions:
  name: ultimatesensor-mini
  friendly_name: UltimateSensor Mini
packages:
  smarthomeshop.ultimatesensor_mini: github://smarthomeshop/ultimatesensor-mini/ultimatesensor-mini-v1/ultimatesensor-mini-basic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: keyssss=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

```
INFO ESPHome 2025.6.0
INFO Reading configuration /config/esphome/ultimatesensor-mini.yaml...
Failed config

esp32: [source /data/packages/4983a4d1/ultimatesensor-mini-v1/ultimatesensor-mini-basic.yaml:27]
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  
  Could not find file '/config/esphome/default_16MB.csv'. Please make sure it exists (full path: /config/esphome/default_16MB.csv).
  partitions: default_16MB.csv
  framework: 
    type: arduino```
